### ISSUE TITLE
Unauthorized : Sorry, you are not authorized to access this page.

### ISSUE THREAD

**Issue by ellemaker** [bigcommerce/stencil-cli#361]
Hi All,

I'm stack on this message when ever I run localhost:3000 in my browser ('Unauthorized : Sorry, you are not authorized to access this page.'), can somebody help me with this. 

thanks you

**Comment by creativewhs** [comment]
@ellemaker Are you still having this issue?
I had this issue and I just fixed it by creating a new set of API Credentials.

**Comment by jkanive** [comment]
@ellemaker , one other reason could be that you have to given an invalid website address. If you have the trial version then click on view store link and provide that url as the when you are initializing stencil. Else if you have a live site running then you have to give that address. If you give "http://www.buysomejunk.com" like it says in the youtube tutorial then you will get that error because the auth token and client id you have generated is for some other site.
Hope that helps.

**Comment by ellemaker** [comment]
@creativewhs and @jkanive thank you all, i already solve this problem by creating a new set of API Credentials... thanks 😄
