### ISSUE TITLE
403 forbidden issue while pushing(upload) the themes to big commerce with stencil files(using builds)

### ISSUE THREAD

**Issue by mahammad13** [bigcommerce/stencil-cli#495]
### Steps to reproduce behavior
![image](https://user-images.githubusercontent.com/41624407/61140455-1baa6d80-a4e9-11e9-8939-e1d18de397e7.png)

Please help me on this issue.

Thanks,
Mahammad

**Comment by karen-white** [comment]
@mahammad13 Are you able to upload the theme manually, through the control panel? This would help us narrow down whether the issue is with the theme bundle or the stencil push command. When you upload through the control panel, you should also see an error code in the network request that may help shed some light on the issue:
https://developer.bigcommerce.com/stencil-docs/prepare-and-upload-a-theme/troubleshooting-theme-uploads#troubleshooting-theme-uploads_error-codes

Please let us know what you find. Thanks!

**Comment by mahammad13** [comment]
Hi Karen,
Thanks for your inputs ...
currently i am uploading the theme using build(azure devops) and using .stencil file(mv -f .stencil 1 stencil (rename the stencil1 file to .stencil))
Please help me on this issue and is there any way to upload the theme by using build & releases.
kindly share your suggestions and solutions.

Thanks,
Mahammad

**Comment by karen-white** [comment]
Hi @mammad13, yes, you certainly can upload the theme using automated builds and releases, but for the sake of troubleshooting, it might help to see whether you can upload the theme through the control panel. That will tell us whether the issue is with the theme bundle (and give us more details about what that issue might be). If the manual upload works, we can focus on troubleshooting your credentials and the stencil push process.
