### ISSUE TITLE
As a theme developer, I should be able to open the storefront/theme editor locally

### ISSUE THREAD

**Issue by steve-ross** [bigcommerce/stencil-cli#601]
### Expected behavior
The stencil-cli allows developers to test configurable storefront options by using the storefront customizer on their local machines.

### Actual behavior
Looks like this option has been removed from stencil-cli

### Steps to reproduce behavior
```sh
stencil start -e
```

Removed theme editor in release 2.1 REF: https://github.com/bigcommerce/stencil-cli/commit/5f18c44348c09852ec41c921be061ad556017562

**Comment by junedkazi** [comment]
@steve-ross yes it was deprecated since the one in cli and the one exposed in the stores no longer matched and provided the same user experience. In its place we have added a small validator which validates your `schema.json` file. 

We are looking what the future of cli and theme editor look like. But for now you will have to bundle and test it on a store.

**Comment by LordZardeck** [comment]
@junedkazi Yeah, this was a big deal at my agency. It helped tremendously. BigCommerce Development is already sub-par with having to test things by deploying them live first, it was nice to at least test the theme editor changes. My team will have to be locked to V1 until this comes back. Is there anywhere we can follow updates on this? Also, this might be a good issue to pin.
