### ISSUE TITLE
Stencil Install Error Cannot Download node-sass

### ISSUE THREAD

**Issue by chandlertrinity** [bigcommerce/stencil-cli#677]
### Expected behavior
I am trying to install Stencil CLI and I keep getting this error and I am not behind a firewall.

### Actual behavior
**This is the terminal when I run:** 
npm install -g @bigcommerce/stencil-cli

```
> @bigcommerce/node-sass@3.5.0 install /Users/chandlerwilcox/.npm-global/lib/node_modules/~/.nvm/versions/node/v12.20.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass
> node scripts/install.js

WARN invalid config loglevel="notice"
Cannot download "https://github.com/bigcommerce-labs/node-sass/releases/download/v3.5.0/darwin-x64-88_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> spawn-sync@1.0.15 postinstall /Users/chandlerwilcox/.npm-global/lib/node_modules/~/.nvm/versions/node/v12.20.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/spawn-sync
> node postinstall


> @bigcommerce/node-sass@3.5.0 postinstall /Users/chandlerwilcox/.npm-global/lib/node_modules/~/.nvm/versions/node/v12.20.1/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass
> node scripts/build.js
```

### Steps to reproduce behavior

MacOS 11.1
Node 12.20.1

I am using .npm-global in my home folder so I don't have permission issues when installing packages

Any help would be greatly appreciated!

**Comment by obrien-k** [comment]
Hey there, could you share more details about the system you're running this on? For example, is this running on a M1 MacBook or Mac mini? Was the Stencil CLI previously working on this machine?

**Comment by MaxGenash** [comment]
It's strange. Seems like your PC tries to download node-sass for node v15 (in "darwin-x64-88", 88 is node modules version of node 15, see https://nodejs.org/en/download/releases ).
So you get 404 because we don’t have a build for node 15 yet ( https://github.com/bigcommerce-labs/node-sass/releases ).

Try removing and reinstalling the global node_modules of the selected node version. Also, make sure that "node -v" tells "12..." in your terminal. Sometimes you can have different node versions in different terminals.
Also, I'd try reinstalling or changing the version of nvm, maybe there is a bug in nvm itself.

**Comment by chandlertrinity** [comment]
@MaxGenash You were spot on.  I guess nvm doesn't persist or override a system version of node.  I had node 15 installed previously.  To fix I had to ditch nvm entirely and download node v12 from their website to install system wide.  After this stencil installed and is running.  Thanks for your help!
